name: PrivPrac
main: me.privileged.prac.main.Main
version: 1.0
author: Privileged

commands:
  info:
    description: "Shows info for given player"
  prac:
    description: "Main practice command"
    aliases: ['practice', 'privprac'] 