name: PrivPrac
main: me.privileged.prac.main.Main
version: 1.0
author: Privileged

commands:
  build:
    description: "Toggles build mode"
  info:
    description: "Shows info for given player"